### ISSUE TITLE
Support `I` and `II` for 1st and 2nd books

### ISSUE THREAD

**Issue by mskelton** [joshpetit/reference_parser#20]
Appreciate your work on this package!

I'm working on an app that uses ML to recognize verses from printed and typed text, and I've noticed that references such as `II Peter 2:3` are not recognized due to the use of two `I`s instead of the number `2`.

Let me know if adding this makes sense to you and I'll be happy to contribute!

**Comment by joshpetit** [comment]
Done, updated to 3.0.3 and it should work. I added support for the whole (unabbreviated) book names

side note: Sadly this library was not written very well, so I would love to do a refactor one day that would make feature requests like this easy and the API generally nice. If you would like to add the abbreviated versions you can see what I did in 9b36e83 and send a pr for any other variations you want to add. 

Your project sounds exciting, if you could send me a link to it while you're developing it or done I'd love to take a look.

**Comment by mskelton** [comment]
The project is still really rough, but here it is. https://github.com/mskelton/biblens

Also, I'm just starting to learn Dart/Flutter, so I'm certain there are plenty of things in the project that I'm not doing right :)  TypeScript and React is what I use on a daily basis, so it's taking some time to learn a different paradigm.

**Comment by joshpetit** [comment]
Fantastic stuff. If you need anything or are hitting your head against the wall with flutter feel free to shoot me an email at joshua@petit.dev and I'm more than happy to help you. Hoping the best!

**Comment by joshpetit** [comment]
Just as a by the way @mskelton . I'm planning on creating a v4 that will allow people to add their own mappings from strings to books. You can look at the API considerations I'm making here: https://github.com/joshpetit/reference_parser/blob/v4/docs/V4_README.md. Let me know if you have any thing in specific that would help you in your project.

**Comment by mskelton** [comment]
@joshpetit Thanks for the heads up. Custom mappings would be awesome.  The only other thing I would say that I've noticed is that the paratext mappings don't seem to be exactly correct. For example John should be JHN, but it's JOH instead. In my app I had to write a custom mapping for that since I couldn't just use `abbrBook`.

**Comment by joshpetit** [comment]
Sounds good, I'll keep that noted.
