### ISSUE TITLE
Reference endVerse uses start chapter to determine last verse

### ISSUE THREAD

**Issue by mazz** [joshpetit/reference_parser#22]
This appears to be a bug when creating a Reference. I think it shouldn't be `schp`(start chapter) to get the end verse. It should be using `echp`(end chapter).

```
        endVerse = evn != null
            ? Verse(book, schp, evn)
            : svn != null
                ? Verse(book, schp, svn)
                : Librarian.getLastVerse(book, schp),
```

https://github.com/joshpetit/reference_parser/blob/666d77fca3fb500b12d33427efdaa4f49eeb6e7f/lib/src/model/Reference.dart#L103

**Comment by mazz** [comment]
Closing this because I think it's actually OK based upon experimentation.

**Comment by joshpetit** [comment]
Yeaa not the most beautiful of apis. I'm planning to overhaul this and make it a lot more maintainable and easier to work with https://github.com/joshpetit/reference_parser/blob/v4/docs/V4_README.md

Hoping to get time and finish it by end of October.

**Comment by mazz** [comment]
@joshpetit I'm actually in the middle of making an Elixir version. I'm probably about 40% done.

**Comment by mazz** [comment]
@joshpetit it's done!

https://github.com/mazz/bible_ex

**Comment by joshpetit** [comment]
Awesome stuff!
